---
- hosts: localhost
  connection: local
  gather_facts: false
  name: Ansible Tower - Job Template Demonstration
  tasks:

    - name: Read Vault Vars
      include_vars: tower_vault.yaml

    - name: Create Job Template 
      tower_job_template:
        name: "{{ item.name }}"
        job_type: run
        inventory: "{{ INVENTORY }}"
        project: "{{ PROJECT }}"
        playbook: yum.yaml
        credential: "{{ CREDENTIAL }}"
        job_tags: "{{ item.tag }}"
        become_enabled: yes
        state: present
      loop:
        - { 'name': 'YUM - Update All Packages', 'tag': 'update' }
        - { 'name': 'YUM - Update Security Packages', 'tag': 'security' }
        - { 'name': 'YUM - Update Bugfix Packages', 'tag': 'bugfix' }
        - { 'name': 'YUM - Install Packages', 'tag': 'install' }

