---
- hosts: instance_state_running
  gather_facts: true
  name: YUM - Update and Install Packages
  tasks:

    - name: YUM - Update All Packages
      yum:
        name: '*'
        state: latest
      register: yumstdout  
      tags:
      - all

    - name: YUM - Update Bugfix Packages
      yum:
        name: '*'
        state: latest
        bugfix: yes
      register: yumstdout  
      tags:
      - bugfix
      
    - name: YUM - Update Security Packages
      yum:
        name: '*'
        state: latest
        security: yes
      register: yumstdout  
      tags:
      - security

    - name: YUM - Install Packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ packages_list }}"
      register: yumstdout  
      tags:
      - install

    - debug:
        msg: "{{ yumstdout }}"
